import { createContext, useContext, useState, useEffect } from "react";

export type Language = "pt-PT" | "pt-BR" | "en-US" | "es";

interface Translations {
  [key: string]: {
    [key: string]: string | { [key: string]: string };
  };
}

type FlatTranslations = Record<Language, Record<string, string>>;

const translations: Translations = {
  "pt-PT": {
    // App
    "app.title": "Sistema de Gestão de Facilities - SGF Grupo FRZ",
    "app.welcome": "Bem-vindo",
    
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.home": "Início",
    "nav.inventory": "Inventário",
    "nav.consumables": "Consumíveis",
    "nav.rooms": "Salas",
    "nav.maintenance": "Chamados e suporte",
    "nav.suppliers": "Fornecedores",
    "nav.logout": "Terminar Sessão",
    
    // Home
    "home.title": "Sistema de Gestão de Facilities - SGF Grupo FRZ",
    "home.subtitle": "Centralize operações e melhore a eficiência da sua equipa",
    "home.inventory": "Inventário",
    "home.inventory.desc": "Controlo de entrada/saída e alertas de stock",
    "home.consumables": "Consumíveis",
    "home.consumables.desc": "Gestão de consumo e tendências de estoque",
    "home.rooms": "Salas",
    "home.rooms.desc": "Calendário visual com status em tempo real",
    "home.maintenance": "Chamados e suporte",
    "home.maintenance.desc": "Preventiva e correctiva com priorização",
    "home.suppliers": "Fornecedores",
    "home.suppliers.desc": "Alertas de vencimento e histórico",
    "home.dashboard": "Dashboard",
    "home.dashboard.desc": "KPIs, gráficos e relatórios executivos",
    "home.tips": "Dicas de Utilização",
    "home.tips.maximize": "Maximize a eficiência da sua gestão de facilities",
    "home.tips.1": "Use o Dashboard para monitorar KPIs em tempo real e tomar decisões informadas.",
    "home.tips.2": "Mantenha o Inventário actualizado para evitar stock crítico e desperdícios.",
    "home.tips.3": "Priorize Chamados Urgentes de manutenção para minimizar impactos operacionais.",
    
    // Inventory
    "inventory.title": "Inventário",
    "inventory.subtitle": "Gestão centralizada de materiais e equipamentos",
    "inventory.new": "Novo Item",
    "inventory.filters": "Filtros",
    "inventory.search": "Pesquisar por nome...",
    "inventory.category": "Categoria",
    "inventory.status": "Status",
    "inventory.registered": "Itens Registados",
    "inventory.found": "itens encontrados",
    "inventory.loading": "Carregando...",
    "inventory.empty": "Nenhum item encontrado",
    "inventory.create_first": "Criar primeiro item",
    "inventory.name": "Nome do Item",
    "inventory.quantity": "Quantidade",
    "inventory.min_quantity": "Quantidade Mínima",
    "inventory.unit": "Unidade",
    "inventory.location": "Localização",
    "inventory.add_category": "Adicionar Nova Categoria",
    "inventory.category_name": "Digite o nome da nova categoria de consumível",
    "inventory.category_placeholder": "Ex: Papel, Tinta, etc.",
    "inventory.create": "Criar",
    "inventory.update": "Actualizar",
    "inventory.cancel": "Cancelar",
    "inventory.save": "Guardar",
    "inventory.edit": "Editar",
    "inventory.delete": "Eliminar",
    "inventory.actions": "Ações",
    "inventory.success_created": "Item criado com sucesso!",
    "inventory.success_updated": "Item actualizado com sucesso!",
    "inventory.success_deleted": "Item eliminado com sucesso!",
    "inventory.error": "Erro",
    "inventory.confirm_delete": "Tem certeza que deseja eliminar este item?",
    
    // Consumables
    "consumables.title": "Consumíveis",
    "consumables.subtitle": "Gestão de consumo e tendências de estoque",
    "consumables.new": "Novo Consumível",
    "consumables.space": "Unidade",
    "consumables.select_space": "Seleccione uma unidade",
    "consumables.current_stock": "Estoque Actual",
    "consumables.min_stock": "Estoque Mínimo",
    "consumables.max_stock": "Estoque Máximo",
    "consumables.trend": "Tendência",
    "consumables.view_trend": "Ver Gráfico de Tendência",
    "consumables.weekly_movement": "Movimentação Semanal",
    "consumables.consumption": "Consumo",
    "consumables.no_data": "Sem dados",
    
    // Rooms
    "rooms.title": "Salas",
    "rooms.subtitle": "Gestão de reservas e calendário visual",
    "rooms.new": "Nova Sala",
    "rooms.name": "Nome da Sala",
    "rooms.capacity": "Capacidade",
    "rooms.status": "Status",
    "rooms.available": "Disponível",
    "rooms.occupied": "Ocupada",
    "rooms.maintenance": "Em Manutenção",
    
    // Maintenance
    "maintenance.title": "Chamados e suporte",
    "maintenance.subtitle": "Gestão de chamados preventivos e correctivos",
    "maintenance.new": "Novo Chamado",
    "maintenance.space": "Unidade",
    "maintenance.select_space": "Seleccione uma unidade",
    "maintenance.title_field": "Título",
    "maintenance.description": "Descrição",
    "maintenance.type": "Tipo",
    "maintenance.preventive": "Preventiva",
    "maintenance.corrective": "Correctiva",
    "maintenance.priority": "Prioridade",
    "maintenance.low": "Baixa",
    "maintenance.medium": "Média",
    "maintenance.high": "Alta",
    "maintenance.urgent": "Urgente",
    "maintenance.status": "Status",
    "maintenance.open": "Aberto",
    "maintenance.in_progress": "Em Progresso",
    "maintenance.completed": "Concluído",
    "maintenance.cancelled": "Cancelado",
    "maintenance.table": "Tabela",
    "maintenance.kanban": "Kanban",
    "maintenance.calls": "Chamados",
    "maintenance.calls_found": "chamados encontrados",
    "maintenance.drag_to_change": "Arraste os cards entre as colunas para alterar o status",
    "maintenance.no_calls": "Nenhum chamado",
    "maintenance.create_edit": "Criar/Editar Chamado",
    "maintenance.fill_data": "Preencha os dados do chamado de manutenção",
    "maintenance.edit_call": "Editar Chamado",
    "maintenance.success_created": "Chamado criado com sucesso!",
    "maintenance.success_updated": "Chamado actualizado com sucesso!",
    "maintenance.success_deleted": "Chamado eliminado com sucesso!",
    "maintenance.confirm_delete": "Tem certeza que deseja eliminar este chamado?",
    
    // Suppliers
    "suppliers.title": "Fornecedores",
    "suppliers.subtitle": "Gestão de fornecedores e contratos",
    "suppliers.new": "Novo Fornecedor",
    "suppliers.name": "Nome do Fornecedor",
    "suppliers.contact": "Contacto",
    "suppliers.email": "Email",
    "suppliers.phone": "Telefone",
    "suppliers.address": "Endereço",
    "suppliers.contracts": "Contratos",
    "suppliers.alerts": "Alertas",
    "suppliers.expiration": "Vencimento",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "KPIs, gráficos e relatórios executivos",
    "dashboard.kpis": "KPIs",
    "dashboard.charts": "Gráficos",
    "dashboard.reports": "Relatórios",
    
    // Common
    "common.language": "Idioma",
    "common.add": "Adicionar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.confirm": "Confirmar",
    "common.close": "Fechar",
    "common.loading": "Carregando...",
    "common.error": "Erro",
    "common.success": "Sucesso",
    "common.warning": "Aviso",
    "common.info": "Informação",
    "common.no_data": "Sem dados",
    "common.search": "Pesquisar",
    "common.filter": "Filtrar",
    "common.sort": "Ordenar",
    "common.export": "Exportar",
    "common.import": "Importar",
    "common.print": "Imprimir",
    "common.back": "Voltar",
    "common.next": "Próximo",
    "common.previous": "Anterior",
    "common.yes": "Sim",
    "common.no": "Não",
  },
  
  "pt-BR": {
    // App
    "app.title": "Sistema de Gestão de Facilities - SGF Grupo FRZ",
    "app.welcome": "Bem-vindo",
    
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.home": "Início",
    "nav.inventory": "Inventário",
    "nav.consumables": "Consumíveis",
    "nav.rooms": "Salas",
    "nav.maintenance": "Chamados e suporte",
    "nav.suppliers": "Fornecedores",
    "nav.logout": "Sair",
    
    // Home
    "home.title": "Sistema de Gestão de Facilities - SGF Grupo FRZ",
    "home.subtitle": "Centralize operações e melhore a eficiência da sua equipe",
    "home.inventory": "Inventário",
    "home.inventory.desc": "Controle de entrada/saída e alertas de estoque",
    "home.consumables": "Consumíveis",
    "home.consumables.desc": "Gestão de consumo e tendências de estoque",
    "home.rooms": "Salas",
    "home.rooms.desc": "Calendário visual com status em tempo real",
    "home.maintenance": "Chamados e suporte",
    "home.maintenance.desc": "Preventiva e corretiva com priorização",
    "home.suppliers": "Fornecedores",
    "home.suppliers.desc": "Alertas de vencimento e histórico",
    "home.dashboard": "Dashboard",
    "home.dashboard.desc": "KPIs, gráficos e relatórios executivos",
    "home.tips": "Dicas de Utilização",
    "home.tips.maximize": "Maximize a eficiência da sua gestão de facilities",
    "home.tips.1": "Use o Dashboard para monitorar KPIs em tempo real e tomar decisões informadas.",
    "home.tips.2": "Mantenha o Inventário atualizado para evitar estoque crítico e desperdícios.",
    "home.tips.3": "Priorize Chamados Urgentes de manutenção para minimizar impactos operacionais.",
    
    // Inventory
    "inventory.title": "Inventário",
    "inventory.subtitle": "Gestão centralizada de materiais e equipamentos",
    "inventory.new": "Novo Item",
    "inventory.filters": "Filtros",
    "inventory.search": "Pesquisar por nome...",
    "inventory.category": "Categoria",
    "inventory.status": "Status",
    "inventory.registered": "Itens Registrados",
    "inventory.found": "itens encontrados",
    "inventory.loading": "Carregando...",
    "inventory.empty": "Nenhum item encontrado",
    "inventory.create_first": "Criar primeiro item",
    "inventory.name": "Nome do Item",
    "inventory.quantity": "Quantidade",
    "inventory.min_quantity": "Quantidade Mínima",
    "inventory.unit": "Unidade",
    "inventory.location": "Localização",
    "inventory.add_category": "Adicionar Nova Categoria",
    "inventory.category_name": "Digite o nome da nova categoria de consumível",
    "inventory.category_placeholder": "Ex: Papel, Tinta, etc.",
    "inventory.create": "Criar",
    "inventory.update": "Atualizar",
    "inventory.cancel": "Cancelar",
    "inventory.save": "Guardar",
    "inventory.edit": "Editar",
    "inventory.delete": "Eliminar",
    "inventory.actions": "Ações",
    "inventory.success_created": "Item criado com sucesso!",
    "inventory.success_updated": "Item atualizado com sucesso!",
    "inventory.success_deleted": "Item eliminado com sucesso!",
    "inventory.error": "Erro",
    "inventory.confirm_delete": "Tem certeza que deseja eliminar este item?",
    
    // Consumables
    "consumables.title": "Consumíveis",
    "consumables.subtitle": "Gestão de consumo e tendências de estoque",
    "consumables.new": "Novo Consumível",
    "consumables.space": "Unidade",
    "consumables.select_space": "Selecione uma unidade",
    "consumables.current_stock": "Estoque Atual",
    "consumables.min_stock": "Estoque Mínimo",
    "consumables.max_stock": "Estoque Máximo",
    "consumables.trend": "Tendência",
    "consumables.view_trend": "Ver Gráfico de Tendência",
    "consumables.weekly_movement": "Movimentação Semanal",
    "consumables.consumption": "Consumo",
    "consumables.no_data": "Sem dados",
    
    // Rooms
    "rooms.title": "Salas",
    "rooms.subtitle": "Gestão de reservas e calendário visual",
    "rooms.new": "Nova Sala",
    "rooms.name": "Nome da Sala",
    "rooms.capacity": "Capacidade",
    "rooms.status": "Status",
    "rooms.available": "Disponível",
    "rooms.occupied": "Ocupada",
    "rooms.maintenance": "Em Manutenção",
    
    // Maintenance
    "maintenance.title": "Chamados e suporte",
    "maintenance.subtitle": "Gestão de chamados preventivos e corretivos",
    "maintenance.new": "Novo Chamado",
    "maintenance.space": "Unidade",
    "maintenance.select_space": "Selecione uma unidade",
    "maintenance.title_field": "Título",
    "maintenance.description": "Descrição",
    "maintenance.type": "Tipo",
    "maintenance.preventive": "Preventiva",
    "maintenance.corrective": "Corretiva",
    "maintenance.priority": "Prioridade",
    "maintenance.low": "Baixa",
    "maintenance.medium": "Média",
    "maintenance.high": "Alta",
    "maintenance.urgent": "Urgente",
    "maintenance.status": "Status",
    "maintenance.open": "Aberto",
    "maintenance.in_progress": "Em Progresso",
    "maintenance.completed": "Concluído",
    "maintenance.cancelled": "Cancelado",
    "maintenance.table": "Tabela",
    "maintenance.kanban": "Kanban",
    "maintenance.calls": "Chamados",
    "maintenance.calls_found": "chamados encontrados",
    "maintenance.drag_to_change": "Arraste os cards entre as colunas para alterar o status",
    "maintenance.no_calls": "Nenhum chamado",
    "maintenance.create_edit": "Criar/Editar Chamado",
    "maintenance.fill_data": "Preencha os dados do chamado de manutenção",
    "maintenance.edit_call": "Editar Chamado",
    "maintenance.success_created": "Chamado criado com sucesso!",
    "maintenance.success_updated": "Chamado atualizado com sucesso!",
    "maintenance.success_deleted": "Chamado eliminado com sucesso!",
    "maintenance.confirm_delete": "Tem certeza que deseja eliminar este chamado?",
    
    // Suppliers
    "suppliers.title": "Fornecedores",
    "suppliers.subtitle": "Gestão de fornecedores e contratos",
    "suppliers.new": "Novo Fornecedor",
    "suppliers.name": "Nome do Fornecedor",
    "suppliers.contact": "Contato",
    "suppliers.email": "Email",
    "suppliers.phone": "Telefone",
    "suppliers.address": "Endereço",
    "suppliers.contracts": "Contratos",
    "suppliers.alerts": "Alertas",
    "suppliers.expiration": "Vencimento",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "KPIs, gráficos e relatórios executivos",
    "dashboard.kpis": "KPIs",
    "dashboard.charts": "Gráficos",
    "dashboard.reports": "Relatórios",
    
    // Common
    "common.language": "Idioma",
    "common.add": "Adicionar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.confirm": "Confirmar",
    "common.close": "Fechar",
    "common.loading": "Carregando...",
    "common.error": "Erro",
    "common.success": "Sucesso",
    "common.warning": "Aviso",
    "common.info": "Informação",
    "common.no_data": "Sem dados",
    "common.search": "Pesquisar",
    "common.filter": "Filtrar",
    "common.sort": "Ordenar",
    "common.export": "Exportar",
    "common.import": "Importar",
    "common.print": "Imprimir",
    "common.back": "Voltar",
    "common.next": "Próximo",
    "common.previous": "Anterior",
    "common.yes": "Sim",
    "common.no": "Não",
  },
  
  "en-US": {
    // App
    "app.title": "Facilities Management System - SGA Grupo FRZ",
    "app.welcome": "Welcome",
    
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.home": "Home",
    "nav.inventory": "Inventory",
    "nav.consumables": "Consumables",
    "nav.rooms": "Rooms",
    "nav.maintenance": "Support tickets",
    "nav.suppliers": "Suppliers",
    "nav.logout": "Logout",
    
    // Home
    "home.title": "Facilities Management System - SGA Grupo FRZ",
    "home.subtitle": "Centralize operations and improve your team's efficiency",
    "home.inventory": "Inventory",
    "home.inventory.desc": "Inbound/outbound control and stock alerts",
    "home.consumables": "Consumables",
    "home.consumables.desc": "Consumption management and stock trends",
    "home.rooms": "Rooms",
    "home.rooms.desc": "Visual calendar with real-time status",
    "home.maintenance": "Support tickets",
    "home.maintenance.desc": "Preventive and corrective with prioritization",
    "home.suppliers": "Suppliers",
    "home.suppliers.desc": "Expiration alerts and history",
    "home.dashboard": "Dashboard",
    "home.dashboard.desc": "KPIs, charts and executive reports",
    "home.tips": "Usage Tips",
    "home.tips.maximize": "Maximize the efficiency of your facilities management",
    "home.tips.1": "Use the Dashboard to monitor KPIs in real-time and make informed decisions.",
    "home.tips.2": "Keep Inventory updated to avoid critical stock and waste.",
    "home.tips.3": "Prioritize Urgent Maintenance Calls to minimize operational impacts.",
    
    // Inventory
    "inventory.title": "Inventory",
    "inventory.subtitle": "Centralized management of materials and equipment",
    "inventory.new": "New Item",
    "inventory.filters": "Filters",
    "inventory.search": "Search by name...",
    "inventory.category": "Category",
    "inventory.status": "Status",
    "inventory.registered": "Registered Items",
    "inventory.found": "items found",
    "inventory.loading": "Loading...",
    "inventory.empty": "No items found",
    "inventory.create_first": "Create first item",
    "inventory.name": "Item Name",
    "inventory.quantity": "Quantity",
    "inventory.min_quantity": "Minimum Quantity",
    "inventory.unit": "Unit",
    "inventory.location": "Location",
    "inventory.add_category": "Add New Category",
    "inventory.category_name": "Enter the name of the new consumable category",
    "inventory.category_placeholder": "Ex: Paper, Ink, etc.",
    "inventory.create": "Create",
    "inventory.update": "Update",
    "inventory.cancel": "Cancel",
    "inventory.save": "Save",
    "inventory.edit": "Edit",
    "inventory.delete": "Delete",
    "inventory.actions": "Actions",
    "inventory.success_created": "Item created successfully!",
    "inventory.success_updated": "Item updated successfully!",
    "inventory.success_deleted": "Item deleted successfully!",
    "inventory.error": "Error",
    "inventory.confirm_delete": "Are you sure you want to delete this item?",
    
    // Consumables
    "consumables.title": "Consumables",
    "consumables.subtitle": "Consumption management and stock trends",
    "consumables.new": "New Consumable",
    "consumables.space": "Unit",
    "consumables.select_space": "Select a unit",
    "consumables.current_stock": "Current Stock",
    "consumables.min_stock": "Minimum Stock",
    "consumables.max_stock": "Maximum Stock",
    "consumables.trend": "Trend",
    "consumables.view_trend": "View Trend Chart",
    "consumables.weekly_movement": "Weekly Movement",
    "consumables.consumption": "Consumption",
    "consumables.no_data": "No data",
    
    // Rooms
    "rooms.title": "Rooms",
    "rooms.subtitle": "Reservation management and visual calendar",
    "rooms.new": "New Room",
    "rooms.name": "Room Name",
    "rooms.capacity": "Capacity",
    "rooms.status": "Status",
    "rooms.available": "Available",
    "rooms.occupied": "Occupied",
    "rooms.maintenance": "Under Maintenance",
    
    // Maintenance
    "maintenance.title": "Support tickets",
    "maintenance.subtitle": "Management of preventive and corrective calls",
    "maintenance.new": "New Call",
    "maintenance.space": "Unit",
    "maintenance.select_space": "Select a unit",
    "maintenance.title_field": "Title",
    "maintenance.description": "Description",
    "maintenance.type": "Type",
    "maintenance.preventive": "Preventive",
    "maintenance.corrective": "Corrective",
    "maintenance.priority": "Priority",
    "maintenance.low": "Low",
    "maintenance.medium": "Medium",
    "maintenance.high": "High",
    "maintenance.urgent": "Urgent",
    "maintenance.status": "Status",
    "maintenance.open": "Open",
    "maintenance.in_progress": "In Progress",
    "maintenance.completed": "Completed",
    "maintenance.cancelled": "Cancelled",
    "maintenance.table": "Table",
    "maintenance.kanban": "Kanban",
    "maintenance.calls": "Calls",
    "maintenance.calls_found": "calls found",
    "maintenance.drag_to_change": "Drag cards between columns to change status",
    "maintenance.no_calls": "No calls",
    "maintenance.create_edit": "Create/Edit Call",
    "maintenance.fill_data": "Fill in the maintenance call data",
    "maintenance.edit_call": "Edit Call",
    "maintenance.success_created": "Call created successfully!",
    "maintenance.success_updated": "Call updated successfully!",
    "maintenance.success_deleted": "Call deleted successfully!",
    "maintenance.confirm_delete": "Are you sure you want to delete this call?",
    
    // Suppliers
    "suppliers.title": "Suppliers",
    "suppliers.subtitle": "Supplier and contract management",
    "suppliers.new": "New Supplier",
    "suppliers.name": "Supplier Name",
    "suppliers.contact": "Contact",
    "suppliers.email": "Email",
    "suppliers.phone": "Phone",
    "suppliers.address": "Address",
    "suppliers.contracts": "Contracts",
    "suppliers.alerts": "Alerts",
    "suppliers.expiration": "Expiration",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "KPIs, charts and executive reports",
    "dashboard.kpis": "KPIs",
    "dashboard.charts": "Charts",
    "dashboard.reports": "Reports",
    
    // Common
    "common.language": "Language",
    "common.add": "Add",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.close": "Close",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.warning": "Warning",
    "common.info": "Information",
    "common.no_data": "No data",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.export": "Export",
    "common.import": "Import",
    "common.print": "Print",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.yes": "Yes",
    "common.no": "No",
  },
  
  "es": {
    // App
    "app.title": "Sistema de Gestión de Facilities - SGA Grupo FRZ",
    "app.welcome": "Bienvenido",
    
    // Navigation
    "nav.dashboard": "Panel",
    "nav.home": "Inicio",
    "nav.inventory": "Inventario",
    "nav.consumables": "Consumibles",
    "nav.rooms": "Salas",
    "nav.maintenance": "Soporte y tickets",
    "nav.suppliers": "Proveedores",
    "nav.logout": "Cerrar Sesión",
    
    // Home
    "home.title": "Sistema de Gestión de Facilities - SGA Grupo FRZ",
    "home.subtitle": "Centralice operaciones y mejore la eficiencia de su equipo",
    "home.inventory": "Inventario",
    "home.inventory.desc": "Control de entrada/salida y alertas de stock",
    "home.consumables": "Consumibles",
    "home.consumables.desc": "Gestión de consumo y tendencias de stock",
    "home.rooms": "Salas",
    "home.rooms.desc": "Calendario visual con estado en tiempo real",
    "home.maintenance": "Soporte y tickets",
    "home.maintenance.desc": "Preventivo y correctivo con priorización",
    "home.suppliers": "Proveedores",
    "home.suppliers.desc": "Alertas de vencimiento e historial",
    "home.dashboard": "Panel",
    "home.dashboard.desc": "KPIs, gráficos e informes ejecutivos",
    "home.tips": "Consejos de Uso",
    "home.tips.maximize": "Maximice la eficiencia de su gestión de facilities",
    "home.tips.1": "Use el Panel para monitorear KPIs en tiempo real y tomar decisiones informadas.",
    "home.tips.2": "Mantenga el Inventario actualizado para evitar stock crítico y desperdicio.",
    "home.tips.3": "Priorice Llamadas Urgentes de mantenimiento para minimizar impactos operacionales.",
    
    // Inventory
    "inventory.title": "Inventario",
    "inventory.subtitle": "Gestión centralizada de materiales y equipos",
    "inventory.new": "Nuevo Artículo",
    "inventory.filters": "Filtros",
    "inventory.search": "Buscar por nombre...",
    "inventory.category": "Categoría",
    "inventory.status": "Estado",
    "inventory.registered": "Artículos Registrados",
    "inventory.found": "artículos encontrados",
    "inventory.loading": "Cargando...",
    "inventory.empty": "No se encontraron artículos",
    "inventory.create_first": "Crear primer artículo",
    "inventory.name": "Nombre del Artículo",
    "inventory.quantity": "Cantidad",
    "inventory.min_quantity": "Cantidad Mínima",
    "inventory.unit": "Unidad",
    "inventory.location": "Ubicación",
    "inventory.add_category": "Agregar Nueva Categoría",
    "inventory.category_name": "Ingrese el nombre de la nueva categoría de consumible",
    "inventory.category_placeholder": "Ej: Papel, Tinta, etc.",
    "inventory.create": "Crear",
    "inventory.update": "Actualizar",
    "inventory.cancel": "Cancelar",
    "inventory.save": "Guardar",
    "inventory.edit": "Editar",
    "inventory.delete": "Eliminar",
    "inventory.actions": "Acciones",
    "inventory.success_created": "¡Artículo creado exitosamente!",
    "inventory.success_updated": "¡Artículo actualizado exitosamente!",
    "inventory.success_deleted": "¡Artículo eliminado exitosamente!",
    "inventory.error": "Error",
    "inventory.confirm_delete": "¿Está seguro de que desea eliminar este artículo?",
    
    // Consumables
    "consumables.title": "Consumibles",
    "consumables.subtitle": "Gestión de consumo y tendencias de stock",
    "consumables.new": "Nuevo Consumible",
    "consumables.space": "Unidad",
    "consumables.select_space": "Seleccione una unidad",
    "consumables.current_stock": "Stock Actual",
    "consumables.min_stock": "Stock Mínimo",
    "consumables.max_stock": "Stock Máximo",
    "consumables.trend": "Tendencia",
    "consumables.view_trend": "Ver Gráfico de Tendencia",
    "consumables.weekly_movement": "Movimiento Semanal",
    "consumables.consumption": "Consumo",
    "consumables.no_data": "Sin datos",
    
    // Rooms
    "rooms.title": "Salas",
    "rooms.subtitle": "Gestión de reservas y calendario visual",
    "rooms.new": "Nueva Sala",
    "rooms.name": "Nombre de la Sala",
    "rooms.capacity": "Capacidad",
    "rooms.status": "Estado",
    "rooms.available": "Disponible",
    "rooms.occupied": "Ocupada",
    "rooms.maintenance": "En Mantenimiento",
    
    // Maintenance
    "maintenance.title": "Soporte y tickets",
    "maintenance.subtitle": "Gestión de llamadas preventivas y correctivas",
    "maintenance.new": "Nueva Llamada",
    "maintenance.space": "Unidad",
    "maintenance.select_space": "Seleccione una unidad",
    "maintenance.title_field": "Título",
    "maintenance.description": "Descripción",
    "maintenance.type": "Tipo",
    "maintenance.preventive": "Preventivo",
    "maintenance.corrective": "Correctivo",
    "maintenance.priority": "Prioridad",
    "maintenance.low": "Baja",
    "maintenance.medium": "Media",
    "maintenance.high": "Alta",
    "maintenance.urgent": "Urgente",
    "maintenance.status": "Estado",
    "maintenance.open": "Abierto",
    "maintenance.in_progress": "En Progreso",
    "maintenance.completed": "Completado",
    "maintenance.cancelled": "Cancelado",
    "maintenance.table": "Tabla",
    "maintenance.kanban": "Kanban",
    "maintenance.calls": "Llamadas",
    "maintenance.calls_found": "llamadas encontradas",
    "maintenance.drag_to_change": "Arrastre los cards entre columnas para cambiar el estado",
    "maintenance.no_calls": "Sin llamadas",
    "maintenance.create_edit": "Crear/Editar Llamada",
    "maintenance.fill_data": "Complete los datos de la llamada de mantenimiento",
    "maintenance.edit_call": "Editar Llamada",
    "maintenance.success_created": "¡Llamada creada exitosamente!",
    "maintenance.success_updated": "¡Llamada actualizada exitosamente!",
    "maintenance.success_deleted": "¡Llamada eliminada exitosamente!",
    "maintenance.confirm_delete": "¿Está seguro de que desea eliminar esta llamada?",
    
    // Suppliers
    "suppliers.title": "Proveedores",
    "suppliers.subtitle": "Gestión de proveedores y contratos",
    "suppliers.new": "Nuevo Proveedor",
    "suppliers.name": "Nombre del Proveedor",
    "suppliers.contact": "Contacto",
    "suppliers.email": "Email",
    "suppliers.phone": "Teléfono",
    "suppliers.address": "Dirección",
    "suppliers.contracts": "Contratos",
    "suppliers.alerts": "Alertas",
    "suppliers.expiration": "Vencimiento",
    
    // Dashboard
    "dashboard.title": "Panel",
    "dashboard.subtitle": "KPIs, gráficos e informes ejecutivos",
    "dashboard.kpis": "KPIs",
    "dashboard.charts": "Gráficos",
    "dashboard.reports": "Informes",
    
    // Common
    "common.language": "Idioma",
    "common.add": "Agregar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.confirm": "Confirmar",
    "common.close": "Cerrar",
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.warning": "Advertencia",
    "common.info": "Información",
    "common.no_data": "Sin datos",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.sort": "Ordenar",
    "common.export": "Exportar",
    "common.import": "Importar",
    "common.print": "Imprimir",
    "common.back": "Atrás",
    "common.next": "Siguiente",
    "common.previous": "Anterior",
    "common.yes": "Sí",
    "common.no": "No",
  },
};

const forcedPhraseTranslations: Record<string, Record<Language, string>> = {
  "Contratos": {
    "pt-PT": "Contratos",
    "pt-BR": "Contratos",
    "en-US": "Contracts",
    es: "Contratos",
  },
  "Fornecedores e Compras": {
    "pt-PT": "Fornecedores e Compras",
    "pt-BR": "Fornecedores e Compras",
    "en-US": "Suppliers and Purchases",
    es: "Proveedores y Compras",
  },
  "Dashboard Executivo": {
    "pt-PT": "Dashboard Executivo",
    "pt-BR": "Dashboard Executivo",
    "en-US": "Executive Dashboard",
    es: "Panel Ejecutivo",
  },
  "Métricas e indicadores de desempenho": {
    "pt-PT": "Métricas e indicadores de desempenho",
    "pt-BR": "Métricas e indicadores de desempenho",
    "en-US": "Performance metrics and indicators",
    es: "Métricas e indicadores de rendimiento",
  },
  "Salas Disponíveis": {
    "pt-PT": "Salas Disponíveis",
    "pt-BR": "Salas Disponíveis",
    "en-US": "Available Rooms",
    es: "Salas Disponibles",
  },
  "Lista de salas disponíveis para uso no momento.": {
    "pt-PT": "Lista de salas disponíveis para uso no momento.",
    "pt-BR": "Lista de salas disponíveis para uso no momento.",
    "en-US": "List of rooms currently available for use.",
    es: "Lista de salas disponibles para uso en este momento.",
  },
  "Nenhuma sala disponível no momento.": {
    "pt-PT": "Nenhuma sala disponível no momento.",
    "pt-BR": "Nenhuma sala disponível no momento.",
    "en-US": "No rooms available at the moment.",
    es: "No hay salas disponibles en este momento.",
  },
  "Clique para utilizar esta sala": {
    "pt-PT": "Clique para utilizar esta sala",
    "pt-BR": "Clique para utilizar esta sala",
    "en-US": "Click to use this room",
    es: "Haga clic para usar esta sala",
  },
  "Utilizar Sala": {
    "pt-PT": "Utilizar Sala",
    "pt-BR": "Utilizar Sala",
    "en-US": "Use Room",
    es: "Usar Sala",
  },
  "Nome do Solicitante *": {
    "pt-PT": "Nome do Solicitante *",
    "pt-BR": "Nome do Solicitante *",
    "en-US": "Requester Name *",
    es: "Nombre del Solicitante *",
  },
  "Data de Início *": {
    "pt-PT": "Data de Início *",
    "pt-BR": "Data de Início *",
    "en-US": "Start Date *",
    es: "Fecha de Inicio *",
  },
  "Data de Fim *": {
    "pt-PT": "Data de Fim *",
    "pt-BR": "Data de Fim *",
    "en-US": "End Date *",
    es: "Fecha de Fin *",
  },
  "Hora de Início": {
    "pt-PT": "Hora de Início",
    "pt-BR": "Hora de Início",
    "en-US": "Start Time",
    es: "Hora de Inicio",
  },
  "Hora de Fim": {
    "pt-PT": "Hora de Fim",
    "pt-BR": "Hora de Fim",
    "en-US": "End Time",
    es: "Hora de Fin",
  },
  "Confirmar Uso": {
    "pt-PT": "Confirmar Uso",
    "pt-BR": "Confirmar Uso",
    "en-US": "Confirm Use",
    es: "Confirmar Uso",
  },
  "Salvando...": {
    "pt-PT": "A guardar...",
    "pt-BR": "Salvando...",
    "en-US": "Saving...",
    es: "Guardando...",
  },
  "Cancel": {
    "pt-PT": "Cancelar",
    "pt-BR": "Cancelar",
    "en-US": "Cancel",
    es: "Cancelar",
  },
  "Cancelar": {
    "pt-PT": "Cancelar",
    "pt-BR": "Cancelar",
    "en-US": "Cancel",
    es: "Cancelar",
  },
  "Contratos Vencidos ou Próximos": {
    "pt-PT": "Contratos Vencidos ou Próximos",
    "pt-BR": "Contratos Vencidos ou Próximos",
    "en-US": "Expired or Upcoming Contracts",
    es: "Contratos Vencidos o Próximos",
  },
  "Contratos vencidos e contratos com vencimento em até 30 dias.": {
    "pt-PT": "Contratos vencidos e contratos com vencimento em até 30 dias.",
    "pt-BR": "Contratos vencidos e contratos com vencimento em até 30 dias.",
    "en-US": "Expired contracts and contracts due within 30 days.",
    es: "Contratos vencidos y contratos con vencimiento dentro de 30 días.",
  },
  "Nenhum contrato vencido ou próximo de vencer.": {
    "pt-PT": "Nenhum contrato vencido ou próximo de vencer.",
    "pt-BR": "Nenhum contrato vencido ou próximo de vencer.",
    "en-US": "No expired or upcoming contracts.",
    es: "No hay contratos vencidos ni próximos a vencer.",
  },
  "Alertas Críticos": {
    "pt-PT": "Alertas Críticos",
    "pt-BR": "Alertas Críticos",
    "en-US": "Critical Alerts",
    es: "Alertas Críticos",
  },
  "Itens Críticos de Consumíveis": {
    "pt-PT": "Itens Críticos de Consumíveis",
    "pt-BR": "Itens Críticos de Consumíveis",
    "en-US": "Critical Consumable Items",
    es: "Ítems Críticos de Consumibles",
  },
  "Nome completo do responsável": {
    "pt-PT": "Nome completo do responsável",
    "pt-BR": "Nome completo do responsável",
    "en-US": "Full name of the responsible person",
    es: "Nombre completo del responsable",
  },
  "Light": {
    "pt-PT": "Claro",
    "pt-BR": "Claro",
    "en-US": "Light",
    es: "Claro",
  },
  "Dark": {
    "pt-PT": "Escuro",
    "pt-BR": "Escuro",
    "en-US": "Dark",
    es: "Oscuro",
  },
  "Tema": {
    "pt-PT": "Tema",
    "pt-BR": "Tema",
    "en-US": "Theme",
    es: "Tema",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("language") as Language) || "pt-PT";
    }
    return "pt-PT";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  useEffect(() => {
    if (typeof document === "undefined") return;

    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return (translations[language]?.[key] as string) || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
